## 4.2 Universal Functions: Fast Element-Wise Array Functions
A universal function, or _ufunc_, is a function that performs element wise operations on data in ndarrays. You think of them as fast vectorized<br>
wrappers for simple functions that take one or more scalar values and produce one or more scalar results.<br>
<br>
Many ufuncs are simple element-wise transformations, like __sqrt__ or __exp__:

In [2]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

These are referred to as _unary_ ufuncs. Others, such as add or maximum, take two arrays (thus, _binary_ ufuncs) and return a single array as the<br>
result:

In [10]:
x = np.random.randn(8)
y = np.random.randn(8)
display(x)
display(y)


array([-2.11564743,  0.17754635, -0.2955585 ,  2.23522151,  1.62568532,
       -1.00648012, -0.93795044,  1.18300557])

array([-0.50606847, -1.35134692, -0.50425104, -0.36266509, -0.59527247,
        0.87609352,  0.36396871,  0.4514578 ])

In [11]:
np.maximum(x,y)

array([-0.50606847,  0.17754635, -0.2955585 ,  2.23522151,  1.62568532,
        0.87609352,  0.36396871,  1.18300557])

numpy.maximum computed the element-wise maximum of the elements in x and y.<br>
<br>
While not common, a ufunc can return multiple arrays.modf is one example, a vectorized version of the built-in Python divmod; it returns the <br>
fractional and integral parts of a floating-point array:

In [12]:
arr = np.random.randn(7)*5
arr

array([ 1.69075328,  2.34353032,  7.83017051,  1.76417633,  7.83581414,
        7.02678783, 12.40883253])

In [14]:
remainder, whole_part = np.modf(arr)
display(remainder)
display(whole_part)

array([0.69075328, 0.34353032, 0.83017051, 0.76417633, 0.83581414,
       0.02678783, 0.40883253])

array([ 1.,  2.,  7.,  1.,  7.,  7., 12.])

Page.109 for unfunc functions